annotationid: f06d8a03-cd6c-4744-8a42-98540aa27665
contentdisposition: 756150000
enabletracking: false
excludefromsearch: false
filename: .gitignore
hiddenfromsitemap: false
id: 9c2121b6-bd6f-4c12-b1d5-c6e804b20003
isdocument: true
mimetype: application/octet-stream
name: .gitignore
objectid: 9c2121b6-bd6f-4c12-b1d5-c6e804b20003
objecttypecode: adx_webfile
parentpageid: 954c2dec-2b83-485c-9904-b5e633338e9d
partialurl: .gitignore
publishingstateid: 10c1dc87-09da-4744-bfec-d76f3a2ba73e
