/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ValidationsRouteImport } from './routes/validations'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuestionnairesRouteImport } from './routes/questionnaires'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyQuestionnairesRouteImport } from './routes/my-questionnaires'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DataverseRouteImport } from './routes/dataverse'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationsRoute = ValidationsRouteImport.update({
  id: '/validations',
  path: '/validations',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesRoute = QuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuestionnairesRoute = MyQuestionnairesRouteImport.update({
  id: '/my-questionnaires',
  path: '/my-questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DataverseRoute = DataverseRouteImport.update({
  id: '/dataverse',
  path: '/dataverse',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/dataverse': typeof DataverseRoute
  '/documents': typeof DocumentsRoute
  '/dossiers': typeof DossiersRoute
  '/evaluations': typeof EvaluationsRoute
  '/my-questionnaires': typeof MyQuestionnairesRoute
  '/onboarding': typeof OnboardingRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/reports': typeof ReportsRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validations': typeof ValidationsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/dataverse': typeof DataverseRoute
  '/documents': typeof DocumentsRoute
  '/dossiers': typeof DossiersRoute
  '/evaluations': typeof EvaluationsRoute
  '/my-questionnaires': typeof MyQuestionnairesRoute
  '/onboarding': typeof OnboardingRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/reports': typeof ReportsRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validations': typeof ValidationsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/dataverse': typeof DataverseRoute
  '/documents': typeof DocumentsRoute
  '/dossiers': typeof DossiersRoute
  '/evaluations': typeof EvaluationsRoute
  '/my-questionnaires': typeof MyQuestionnairesRoute
  '/onboarding': typeof OnboardingRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/reports': typeof ReportsRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validations': typeof ValidationsRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/calendar'
    | '/dataverse'
    | '/documents'
    | '/dossiers'
    | '/evaluations'
    | '/my-questionnaires'
    | '/onboarding'
    | '/questionnaires'
    | '/reports'
    | '/screening'
    | '/settings'
    | '/users'
    | '/validations'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/calendar'
    | '/dataverse'
    | '/documents'
    | '/dossiers'
    | '/evaluations'
    | '/my-questionnaires'
    | '/onboarding'
    | '/questionnaires'
    | '/reports'
    | '/screening'
    | '/settings'
    | '/users'
    | '/validations'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/calendar'
    | '/dataverse'
    | '/documents'
    | '/dossiers'
    | '/evaluations'
    | '/my-questionnaires'
    | '/onboarding'
    | '/questionnaires'
    | '/reports'
    | '/screening'
    | '/settings'
    | '/users'
    | '/validations'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CalendarRoute: typeof CalendarRoute
  DataverseRoute: typeof DataverseRoute
  DocumentsRoute: typeof DocumentsRoute
  DossiersRoute: typeof DossiersRoute
  EvaluationsRoute: typeof EvaluationsRoute
  MyQuestionnairesRoute: typeof MyQuestionnairesRoute
  OnboardingRoute: typeof OnboardingRoute
  QuestionnairesRoute: typeof QuestionnairesRoute
  ReportsRoute: typeof ReportsRoute
  ScreeningRoute: typeof ScreeningRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ValidationsRoute: typeof ValidationsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validations': {
      id: '/validations'
      path: '/validations'
      fullPath: '/validations'
      preLoaderRoute: typeof ValidationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires': {
      id: '/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof QuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-questionnaires': {
      id: '/my-questionnaires'
      path: '/my-questionnaires'
      fullPath: '/my-questionnaires'
      preLoaderRoute: typeof MyQuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataverse': {
      id: '/dataverse'
      path: '/dataverse'
      fullPath: '/dataverse'
      preLoaderRoute: typeof DataverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CalendarRoute: CalendarRoute,
  DataverseRoute: DataverseRoute,
  DocumentsRoute: DocumentsRoute,
  DossiersRoute: DossiersRoute,
  EvaluationsRoute: EvaluationsRoute,
  MyQuestionnairesRoute: MyQuestionnairesRoute,
  OnboardingRoute: OnboardingRoute,
  QuestionnairesRoute: QuestionnairesRoute,
  ReportsRoute: ReportsRoute,
  ScreeningRoute: ScreeningRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ValidationsRoute: ValidationsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
