displayorder: 2
enablerating: false
enabletracking: false
excludefromsearch: false
feedbackpolicy: 756150000
hiddenfromsitemap: false
id: d8e3b00a-e949-493c-a0fd-c8ead9311ec5
isroot: true
name: site-settings
pagetemplateid: 9508ca14-b65b-471b-b770-3f6f9a2f06ab
parentpageid: a391f661-ffe8-4504-801c-a7af5c23e0bf
partialurl: site-settings
publishingstateid: 10c1dc87-09da-4744-bfec-d76f3a2ba73e
sharedpageconfiguration: false
title: site-settings
